### PR TITLE
Fixed editor breaking on error for validation

### LINKED ISSUE #160: Need to clear data structures on error
If syntax or unsupported you have to full refresh in order to run again.  Something was not cleared when the rework on `view/index.js` was done.

### PR DESCRIPTION
**Pull request by angushtlam**
Fixed #160 

# Description

The editor no longer breaks after the insertion of invalid code.

# Change Log
-`src/interpreter/executor/interpret.js` : Reset output var on evaluate (source of error) 
-`src/view/console/index.js`: Updated console for new data input path
-`src/view/index.js`: Removed Console prop. Handling failure for evaluation of code.

# Manual Test Steps
Describe how a reviewer should test the changes. Include relevant workflows, API calls, etc...
**NOTE: All visual changes PR should include a screenshot**

1. Insert valid code
```
var x = 10;
var x = 100;
```

2. Insert invalid code
```
var x = 10;
vaaaar x = 100;
```

3. Insert valid code again
```
var x = 10;
var x = 100;
```

### CODE REVIEW

File: src/interpreter/executor/interpret.js [hunk 1]
```diff
@@ -9,6 +9,9 @@ let output = [];
 
 // Setup for when we initially check syntax
 export function evaluate(inputCode) {
+  // Reset the previous output list.
+  output = [];
```
Comment (zsmoore) [inline src/interpreter/executor/interpret.js]: This isn't necessary I don't think.  We have a resetInterpreter in `interpreter/executer/index.js` which sets output to null, can we just call that function if the interpreter errors similarly how we do if it is successful

File: src/interpreter/executor/interpret.js [hunk 2]
```diff
@@ -302,20 +305,23 @@ function arithmetic(buffer, inputLine, currentState) {
   let newState = stateEnum.CONSUMED;
   let left = buffer.substring(0, buffer.length - 1);
   switch (buffer[buffer.length - 1]) {
-  case operationsEnum.ADDITION:
+  case operationsEnum.ADDITION: {
```
Comment (zsmoore) [inline src/interpreter/executor/interpret.js]: I fixed this linting issue in my PR

File: src/view/editor/index.js [hunk 3]
```diff
@@ -21,7 +21,7 @@ export default class Editor extends React.Component {
     this.editor.setFontSize(fontSize);
 
     // disable line numbers (for now)
-    this.editor.renderer.setOption('showLineNumbers', false)
+    this.editor.renderer.setOption('showLineNumbers', false);
```
Comment (zsmoore) [inline src/view/editor/index.js]: I also fixed this in my pr not sure if we need both

**Comment by gjbunyea** [comment]
image
Not sure if this is in scope for this PR. If it's not I'll approve. IVI does work after i fix the issue without a page refresh - which this PR does address so that's good!

File: src/interpreter/executor/interpret.js (hunk 1 above)
Comment (angushtlam) [reply src/interpreter/executor/interpret.js]: That's what's causing the error. resetInterpreter isn't doing what it's supposed to.

Comment (angushtlam) [reply src/interpreter/executor/interpret.js]: The problem right now is that `evaluate()` in `interpreter/executor/interpret.js` is not a pure function and it uses the `output` variable in `interpreter/executor/interpret.js` to build the steps for the eventual return value in `evaluate()`. On a syntax error, the output in `interpret.js` never gets reset, causing the hangup.

In the latest update I've renamed the variable in `index.js` to `expressions` to prevent the confusion.

There are 3 solutions
1. This diff: Reset the `interpret.js`'s output variable before execution
2. Make `index.js` and `interpret.js` use the same variable in `state.js` or something.
3. In `interpret.js`, remove the global variable `output` and change the functions to use a local `output` in all functions so it isn't using a global variable to build the program.

As of now, `index.js` runs evaluate and keeps a copy of the output, and handles the individual steps. The current solution does not fix the duplication of the output from `interpret.js`, but I think the current interface and sandboxing used in `index.js` available for the frontend is ideal (meaning solution 2 is not as nice).

I am in favor of solution 1 (this diff) as of now. It's the least disruptive change to the state of the project to fix the problem. I'd like solution 3 too, but I think there's a lot of code to change to support that.

Comment (zsmoore) [reply src/interpreter/executor/interpret.js]: Solution 3 isn't really viable I don't think. The only reason our output is global is so that I can push expressions on during our recursion for evaluating chaining assignments etc. Is there a reason that this issue happens for error but not for regular code? If output is never cleared why don't we have an issue for just subsequent runs?
